import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { ClerkProvider } from "@clerk/nextjs";
import MobileSidebar from "@/components/MobileSidebar";
import { auth } from "@clerk/nextjs/server";
import { ensureDbUserFromClerk } from "@/lib/user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();
  const dbUser = await ensureDbUserFromClerk();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Mobile top bar + drawer */}
          <MobileSidebar userId={userId ?? null} username={dbUser?.username || null} />

          <div className="flex pt-12 md:pt-0">
            <Sidebar />
            <div className="flex-1 min-h-dvh">
              <main className="container-app py-8">{children}</main>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
